Merge trunk into multiarch branch and add patches from Steve Langasek
svn path=/glibc-package/branches/multiarch/; revision=4537

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -90,15 +90,15 @@ then
 	if [ ! -d /var/mail ] && [ ! -L /var/mail ]; then
 	    ln -sf spool/mail /var/mail
 	fi
-	if dpkg --compare-versions "$preversion" lt 2.9-5; then
-	    check="apache2-common apache apache-ssl apache-perl autofs at"
+	if dpkg --compare-versions "$preversion" lt 2.11-1; then
+	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
 	    check="$check boa cucipop courier-authdaemon cron cups exim"
-	    check="$check exim4-base dovecot-common cucipop lprng lpr"
+	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
 	    check="$check lpr-ppd mysql-server nis openbsd-inetd"
-	    check="$check openldapd postfix postfix-tls rsync samba"
+	    check="$check openldapd proftpd postfix postfix-tls rsync samba"
 	    check="$check sasl2-bin slapd smail sendmail snmpd ssh"
 	    check="$check spamassassin vsftpd wu-ftpd wu-ftpd-academ wwwoffle"
-	    check="$check webmin dropbear"
+	    check="$check webmin dropbear gdm"
 	    # NSS services check: NSS_CHECK
 	    if [ -n "$services" ]; then
 
@@ -156,16 +156,26 @@ then
 			else
 			    idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
 			fi
-			echo -n "  $service: stopping..."
-			$idl stop > /dev/null 2>&1 || true
-			sleep 2
-			echo -n "starting..."
-			if $idl start > /dev/null 2>&1; then
-			    echo "done."
-			else
-			    echo "FAILED! ($?)"
-			    failed="$service $failed"
-			fi
+			case "$service" in
+			    gdm)
+				echo -n "  $service: reloading..."
+				if $idl reload > /dev/null 2>&1; then
+				    echo "done."
+				else
+				    echo "FAILED! ($?)"
+				    failed="$service $failed"
+				fi
+				;;
+			    *)
+				echo -n "  $service: restarting..."
+				if $idl restart > /dev/null 2>&1; then
+				    echo "done."
+				else
+				    echo "FAILED! ($?)"
+				    failed="$service $failed"
+				fi
+				;;
+			esac
 		    done
 		    echo
 		    if [ -n "$failed" ]; then
@@ -199,17 +209,12 @@ then
 	    else
 		echo "Nothing to restart."
 	    fi
-	fi # end upgrading and $preversion lt 2.6-1
+	fi # end upgrading and $preversion lt 2.11-1
     fi # Upgrading
 
-    # Generate cache file /usr/lib/gconv/gconv-modules.cache
-    iconvconfig || true
-
-    if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
-      # the devicenumber/inode pair of / is the same as that of /sbin/init's
-      # root, so we're *not* in a chroot
-      (telinit u ; sleep 1)
-    fi
+    # Restart init. If it fails, there is nothing we can do, so 
+    # just ignore the error
+    telinit u 2> /dev/null || true ; sleep 1
 fi
 
 #DEBHELPER#
